Name: Kirshan Chand <br>
Final Project: World Bank Development Indicators<br>
Blog link: https://medium.com/@kchand_13462/how-economic-health-and-digital-factors-shape-country-development-4a340e119384

### __Goal__<br>
How do economic, health, and digital factors influence the well being and development of countries worldwide?

- Do countries with higher education and health expenditure have better life expectancy?
- Are countries with better digital infrastructure also investing more in education or health?
- Did unemployment rise in countries with high inflation or economic instability?
- Which top 10 countries have shown the fastest GDP growth over the past decade?
- Which top 10 countries perform well across health, education, economy, and digitalization?

In [1]:
# Imports libraries
import pandas as pd 
import numpy as np
import plotly.express as px 
import plotly.graph_objects as go
from great_tables import (
    GT, md, style, google_font, loc
)

In [17]:
# Dataset link: https://www.kaggle.com/datasets/yogafsyahputra/worldbank-development
# Load the dataset into a pandas dataframe  
df = pd.read_csv('worldbank_development_indicators.csv')
df

,Country,Country_ISO3,Year,GDP_per_capita_USD,Inflation_annual_pct,Exports_pct_of_GDP,FDI_inflows_pct_of_GDP,Population,Life_expectancy_years,Access_to_electricity_pct,Internet_users_pct,Mobile_subscriptions_per_100,Unemployment_pct,Health_expenditure_pct_GDP,Mortality_rate_under_5,Education_expenditure_pct_GDP,Renewable_energy_pct,Forest_area_pct
0,Afghanistan,AFG,1990,NaN,NaN,NaN,NaN,12045660.0,45.118,NaN,0.0,0.0000,NaN,NaN,180.7,NaN,23.0,1.852782
1,Afghanistan,AFG,1991,NaN,NaN,NaN,NaN,12238879.0,45.521,NaN,NaN,0.0000,8.070,NaN,174.4,NaN,23.7,1.852782
2,Afghanistan,AFG,1992,NaN,NaN,NaN,NaN,13278974.0,46.569,NaN,NaN,0.0000,8.011,NaN,168.5,NaN,27.4,1.852782
3,Afghanistan,AFG,1993,NaN,NaN,NaN,NaN,14943172.0,51.021,NaN,NaN,0.0000,7.888,NaN,163.0,NaN,28.5,1.852782
4,Afghanistan,AFG,1994,NaN,NaN,NaN,NaN,16250794.0,50.969,NaN,NaN,0.0000,7.822,NaN,157.7,NaN,30.1,1.852782
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8608,Zimbabwe,ZWE,2018,2271.852504,10.618866,26.164051,2.101722,15034452.0,60.906,45.4,25.0,85.8627,6.793,4.655271,52.3,2.05049,79.7,45.332093
8609,Zimbabwe,ZWE,2019,1683.913136,255.304991,27.554170,0.970226,15271368.0,61.060,46.7,26.6,86.4094,7.373,3.232678,51.1,NaN,81.0,45.213002
8610,Zimbabwe,ZWE,2020,1730.453910,557.201817,22.293071,0.559613,15526888.0,61.530,52.7,29.3,84.9604,8.621,2.954401,50.1,NaN,84.1,45.093912
8611,Zimbabwe,ZWE,2021,1724.387271,98.546105,22.775238,0.871791,15797210.0,60.135,49.0,37.1,90.2538,9.540,2.785717,47.6,NaN,82.4,44.974822
8612,Zimbabwe,ZWE,2022,2040.546587,104.705171,27.872170,1.027034,16069056.0,62.360,50.1,37.9,88.9958,10.087,3.628807,46.0,NaN,NaN,44.855732

In [3]:
# Show the info about dataset 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8613 entries, 0 to 8612
Data columns (total 18 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Country                        8613 non-null   object
 1   Country_ISO3                   8613 non-null   object
 2   Year                           8613 non-null   int64
 3   GDP_per_capita_USD             8259 non-null   float64
 4   Inflation_annual_pct           7080 non-null   float64
 5   Exports_pct_of_GDP             6978 non-null   float64
 6   FDI_inflows_pct_of_GDP         7578 non-null   float64
 7   Population                     8613 non-null   float64
 8   Life_expectancy_years          8613 non-null   float64
 9   Access_to_electricity_pct      7487 non-null   float64
 10  Internet_users_pct             5866 non-null   float64
 11  Mobile_subscriptions_per_100   8151 non-null   float64
 12  Unemployment_pct               7391 non-null   float64
 13  Health_expenditure_pct_GDP     5350 non-null   float64
 14  Mortality_rate_under_5         7920 non-null   float64
 15  Education_expenditure_pct_GDP  5038 non-null   float64
 16  Renewable_energy_pct           8110 non-null   float64
 17  Forest_area_pct                8279 non-null   float64
dtypes: float64(15), int64(1), object(2)
memory usage: 1.2+ MB

In [4]:
# Show the descriptive statistics of the data
df.describe()

,Year,GDP_per_capita_USD,Inflation_annual_pct,Exports_pct_of_GDP,FDI_inflows_pct_of_GDP,Population,Life_expectancy_years,Access_to_electricity_pct,Internet_users_pct,Mobile_subscriptions_per_100,Unemployment_pct,Health_expenditure_pct_GDP,Mortality_rate_under_5,Education_expenditure_pct_GDP,Renewable_energy_pct,Forest_area_pct
count,8613.000000,8259.000000,7080.000000,6978.000000,7578.000000,8.613000e+03,8613.000000,7487.000000,5866.000000,8151.000000,7391.000000,5350.000000,7920.000000,5038.000000,8110.000000,8279.000000
mean,2006.000000,12241.966940,21.172869,37.815418,6.627608,2.458279e+08,68.959952,81.073648,29.491361,54.676817,7.936840,6.191569,48.779630,4.312888,31.244646,32.577231
std,9.522457,20576.581238,326.651303,28.140543,48.814369,8.219566e+08,9.262708,28.548475,31.348526,53.398912,5.624235,2.818281,51.550845,1.838191,29.685279,23.581753
min,1990.000000,22.952133,-16.859691,0.005377,-1303.108267,8.798000e+03,12.158000,0.533899,0.000000,0.000000,0.100000,1.107200,1.500000,0.000000,0.000000,0.000000
25%,1998.000000,1127.767029,2.060712,21.308669,0.923911,1.314545e+06,63.463000,69.874953,1.430000,1.375138,4.066005,4.214512,11.600000,3.169455,5.800000,11.985524
50%,2006.000000,3751.353190,4.129582,30.364360,2.322874,8.479823e+06,70.795000,98.500000,16.050000,43.227900,6.452012,5.434047,28.100000,4.106236,21.200000,31.175541
75%,2014.000000,14641.726989,8.063461,46.698520,4.582559,4.850035e+07,75.804288,100.000000,55.800000,101.579658,10.284774,7.807724,70.791231,5.175888,53.900000,48.128588
max,2022.000000,226052.001905,23773.131774,433.836004,1709.827232,7.990400e+09,86.151000,100.000000,100.000000,416.261000,38.800000,24.230690,478.900000,44.333981,98.300000,96.226381

In [5]:
# Get all the columns name to understand dataset structure 
df.columns

Index(['Country', 'Country_ISO3', 'Year', 'GDP_per_capita_USD',
       'Inflation_annual_pct', 'Exports_pct_of_GDP', 'FDI_inflows_pct_of_GDP',
       'Population', 'Life_expectancy_years', 'Access_to_electricity_pct',
       'Internet_users_pct', 'Mobile_subscriptions_per_100',
       'Unemployment_pct', 'Health_expenditure_pct_GDP',
       'Mortality_rate_under_5', 'Education_expenditure_pct_GDP',
       'Renewable_energy_pct', 'Forest_area_pct'],
      dtype='object')

In [6]:
#  Rename long and unclear column names to more readable and analysis friendly versions
df = df.rename(columns={
    'GDP_per_capita_USD': 'GDP Per Capita (USD)',
    'Inflation_annual_pct': 'Inflation',
    'Life_expectancy_years': 'Life Expectancy',
    'Education_expenditure_pct_GDP': 'Education Expenditure',
    'Health_expenditure_pct_GDP': 'Health Expenditure',
    'Unemployment_pct': 'Unemployment',
    'Internet_users_pct': 'Internet Users (%)'
})
df.head()

,Country,Country_ISO3,Year,GDP Per Capita (USD),Inflation,Exports_pct_of_GDP,FDI_inflows_pct_of_GDP,Population,Life Expectancy,Access_to_electricity_pct,Internet Users (%),Mobile_subscriptions_per_100,Unemployment,Health Expenditure,Mortality_rate_under_5,Education Expenditure,Renewable_energy_pct,Forest_area_pct
0,Afghanistan,AFG,1990,NaN,NaN,NaN,NaN,12045660.0,45.118,NaN,0.0,0.0,NaN,NaN,180.7,NaN,23.0,1.852782
1,Afghanistan,AFG,1991,NaN,NaN,NaN,NaN,12238879.0,45.521,NaN,NaN,0.0,8.070,NaN,174.4,NaN,23.7,1.852782
2,Afghanistan,AFG,1992,NaN,NaN,NaN,NaN,13278974.0,46.569,NaN,NaN,0.0,8.011,NaN,168.5,NaN,27.4,1.852782
3,Afghanistan,AFG,1993,NaN,NaN,NaN,NaN,14943172.0,51.021,NaN,NaN,0.0,7.888,NaN,163.0,NaN,28.5,1.852782
4,Afghanistan,AFG,1994,NaN,NaN,NaN,NaN,16250794.0,50.969,NaN,NaN,0.0,7.822,NaN,157.7,NaN,30.1,1.852782

##### 1. Do countries with higher education & health expenditure have better life expectancy?

In [7]:
# Filter years 2000–2022
df = df[(df['Year'] >= 2000) & (df['Year'] <= 2022)]

# most recent data for each country
latest = df.sort_values("Year").groupby("Country").tail(1).reset_index(drop=True)
df1 = latest

# Required columns to use
cols = ['Country', 'Education Expenditure', 'Health Expenditure', 'Life Expectancy']

# Combined expenditure
df1['Total Expenditure'] = df1['Education Expenditure'] + df1['Health Expenditure']

In [8]:
# Scatter plot
fig = px.scatter(
    df1,
    x='Total Expenditure',
    y='Life Expectancy',
    hover_name='Country',
    trendline='ols',
    title='<b>Investing in Education and Health Correlates with Higher Life Expectancy',
    subtitle = 'Countries allocating more than 15% of GDP to social spending consistently achieve life expectancies<br>above 80 years, while low spending nations show significantly lower longevity outcomes.',
    labels={
        'Total Expenditure':'Education + Health Expenditure',
        'Life Expectancy':'Life Expectancy (years)'
    },
    height=500,
    width=700
)
# Trendline 
fig.data[-1].line.color = 'red'
# Title styling
fig.update_layout(
    title_font_family="Helvetica",
    title_font_size=18,
    font=dict(family='Helvetica', size=14, color="#1A1A1A"),
    margin = {'t':150}
)
fig.show()

##### 2. Are countries with better digital infrastructure also investing more in education or health?

In [9]:
# Select required columns 
cols = [
    'Country',
    'Year',
    'Education Expenditure',
    'Health Expenditure',
    'Internet Users (%)'
]

df_clean = df[cols].copy()

# cleaning dataset
df_clean = df_clean.dropna() 
df_clean = df_clean.drop_duplicates()

# Keep latest record for each country 
df_latest = (
    df_clean.sort_values('Year')        
           .groupby('Country')          
           .tail(1)                     
           .reset_index(drop=True)
)

# Select top 10 countries with highest Internet Users 
top10 = (
    df_latest.sort_values('Internet Users (%)', ascending=False)
             .head(10)
             .loc[:, ['Country', 'Education Expenditure', 'Health Expenditure', 'Internet Users (%)']]
)

# Rename specific country name (UAE)
top10['Country'] = top10['Country'].replace({'United Arab Emirates': 'UAE'})
# Indexing for Table 
top10.index = range(1, len(top10)+1)
top10_reset = top10.reset_index(drop=True)
top10

        Country  Education Expenditure  Health Expenditure  Internet Users (%)
1           UAE               3.894030            5.304943               100.0
2       Bahrain               1.987797            3.837453               100.0
3       Iceland               7.139665            9.285939                99.8
4         Qatar               3.233670            3.818722                99.7
5        Kuwait               6.582365            4.268758                99.7
6        Monaco               1.173250            3.397797                99.1
7        Norway               3.968020            7.948033                99.0
8    Luxembourg               4.703022            5.551548                98.2
9       Denmark               5.296434            9.475862                97.9
10  Korea, Rep.               4.866270            8.957327                97.6

In [10]:
# Table and heatmap
# Get min and max values for heatmap
minv = top10_reset['Internet Users (%)'].min()
maxv = top10_reset['Internet Users (%)'].max()

# Create GT table with Internet Users highlighted in purple
(
    GT(top10_reset)
    .tab_header(
        title=md("<b>Digital Infrastructure Correlates with Higher Social Spending"),
        subtitle=md("Countries with higher internet penetration consistently allocate more funding to both education and health,<br>confirming a strong link between digital connectivity and social investment.")
    )
    # Dataset source name
    .tab_source_note('Source: World Bank Development Indicators')
    .opt_align_table_header('left')
    # Title styling
    .tab_options(
        heading_title_font_size='22px',
        heading_subtitle_font_size='16px',
        column_labels_font_size='16px',
        table_font_size='16px'
    )
    .tab_style(
        style = style.text(font = google_font(name = "Helvetica")), 
        locations = loc.title()
    )
    # Heatmap
    .data_color(
        columns='Internet Users (%)',   
        domain=[minv, maxv],         
        palette='Purples'              
    )
)

GT(_tbl_data=       Country  Education Expenditure  Health Expenditure  Internet Users (%)
0          UAE               3.894030            5.304943               100.0
1      Bahrain               1.987797            3.837453               100.0
2      Iceland               7.139665            9.285939                99.8
3        Qatar               3.233670            3.818722                99.7
4       Kuwait               6.582365            4.268758                99.7
5       Monaco               1.173250            3.397797                99.1
6       Norway               3.968020            7.948033                99.0
7   Luxembourg               4.703022            5.551548                98.2
8      Denmark               5.296434            9.475862                97.9

##### 3. Did unemployment rise in countries with high inflation or economic instability?

In [11]:
# Select relevant columns and remove duplicates
df_inf = df[['Country', 'Year', 'Inflation', 'Unemployment']].drop_duplicates()

# Identify the most affected country based on average Inflation + Unemployment
country_impact = df_inf.groupby('Country')[['Inflation', 'Unemployment']].mean().sum(axis=1)
most_affected = country_impact.idxmax()

# Filter data for the most affected country and sort by year
df_top = df_inf[df_inf['Country'] == most_affected].sort_values('Year')

# Prepare full timeline values (2000–2022) for Inflation and Unemployment
years_full = list(range(2000, 2023))
inflation_vals = df_top.set_index('Year').reindex(years_full)['Inflation'].tolist()
unemp_vals = df_top.set_index('Year').reindex(years_full)['Unemployment'].tolist()

In [19]:
# line chart
fig = go.Figure()

# Inflation trace
fig.add_trace(go.Scatter(
    x=years_full,
    y=inflation_vals,
    mode='lines',
    name=f'{most_affected} – Inflation',
    line=dict(width=4, color='#d62728')
))

# Unemployment trace
fig.add_trace(go.Scatter(
    x=years_full,
    y=unemp_vals,
    mode='lines',
    name=f'{most_affected} – Unemployment',
    line=dict(width=4, color='#1191ed', dash='dot'),
    yaxis='y2'
))

# Title and subtitle
fig.update_layout(
    title=(
        f"<b>Rising Inflation and Unemployment in Zimbabwe: Trends Over 2000–2022</b><br>"
        "<span style='font-size: 14px'>In this chart, Zimbabwe’s inflation (Red) surged sharply after 2008, while unemployment (Blue) also rose, highlighting<br>the country’s economic instability."
    ),
    title_font_size=18,
    font=dict(family='Helvetica', size=16),
    width=800,
    height=500,
    xaxis=dict(title='Year'),
    yaxis=dict(title='Inflation (%)', showgrid=False),
    yaxis2=dict(title='Unemployment (%)', overlaying='y', side='right', showgrid=False),
    legend_title="Indicators",
    margin={'t':140},
    showlegend=False
)
fig.show()

##### 4. Which countries have shown the fastest GDP growth over the past decade?

In [13]:
# Select required columns 
df1 = df[['Country', 'Year', 'GDP Per Capita (USD)']].dropna()

# Keep only last 10 years 
latest = df1['Year'].max()
df1 = df1[df1['Year'] >= latest - 10]

# Calculate GDP growth 
growth = (
    df1.sort_values(['Country', 'Year'])
       .groupby('Country')
       .agg(start_gdp=('GDP Per Capita (USD)', 'first'),
            end_gdp=('GDP Per Capita (USD)', 'last'))
)

# Percentage growth
growth['GDP Growth (%)'] = (growth['end_gdp'] - growth['start_gdp']) / growth['start_gdp'] * 100

# Top 10 fastest growing
top10_growth = growth['GDP Growth (%)'].nlargest(10).reset_index()
top10_growth

                 Country  GDP Growth (%)
0                 Guyana      229.026173
1             Bangladesh      215.987837
2            Timor-Leste      129.141563
3               Djibouti      123.773187
4               Ethiopia      123.638800
5                Ireland      112.974719
6                 Guinea      102.557987
7                  China      102.505689
8  Sao Tome and Principe       97.369657
9               Cambodia       94.921644

In [ ]:
# Bar chart
# Create 'flag' column to mark the country with highest GDP growth
top10_growth['flag'] = (top10_growth['GDP Growth (%)'] == top10_growth['GDP Growth (%)'].max()).astype(str)
# format GDP growth values to 2 decimal places
top10_growth['GDP Growth Label'] = top10_growth['GDP Growth (%)'].apply(lambda x: f"{x:.2f}")

# Horizontal bar chart
fig = px.bar(
    top10_growth.sort_values(by='GDP Growth (%)', ascending=True),
    x = 'GDP Growth (%)', 
    y = 'Country', 
    template='simple_white', 
    text='GDP Growth Label',
    title = '<b>Top 10 Countries with the Fastest GDP Growth (Last 10 Years)', 
    subtitle='This chart shows GDP per capita growth over the last decade, with Guyana at 229%, Bangladesh at 215%,<br>and Timor-Leste at 129%, highlighting the fastest growing economies.',
    height = 500, 
    width = 750,
    color='flag',  
    color_discrete_sequence=['lightgray', '#1191ed']    
)
# Remove the x and y ticks labels
fig.update_layout(yaxis_ticks="")
fig.update_layout(xaxis_ticks="")

# Title and subtitle styling 
fig.update_layout(
    font=dict(size=16, color="#1A1A1A", family="Helvetica"),
    title_font_family = 'Helvetica', 
    title_font_size = 20, 
    title_subtitle_font_size=15,
    margin = {'t':140},
    showlegend=False
)
# Add thin black border to bars
fig.update_traces(marker_line_width=0.5, marker_line_color="black")
# Extend x-axis a bit beyond max value
fig.update_xaxes(range=[0, top10_growth['GDP Growth (%)'].max() * 1.1])
fig.show()

##### 5. Which top 10 countries perform well across health, education, economy, and digitalization?

In [15]:
# Columns for scoring
score_cols = [
    'GDP Per Capita (USD)',
    'Education Expenditure',
    'Health Expenditure',
    'Internet Users (%)'
]

# Preparing data
latest = df.sort_values("Year").groupby("Country").tail(1).reset_index(drop=True)
score = latest.dropna(subset=score_cols).set_index('Country')[score_cols]
score_norm = (score - score.min()) / (score.max() - score.min())
score_norm['Composite'] = score_norm.mean(axis=1)

# Top 10 by composite score
top10_comp = score_norm.nlargest(10, 'Composite').reset_index()

# Melt for facet bar chart
top10 = top10_comp.melt(
    id_vars='Country',
    value_vars=score_cols,
    var_name='Indicator',
    value_name='Normalized Score'
)

In [16]:
# Facet bar chart
fig = px.bar(
    top10,
    x='Normalized Score',
    y='Country',
    facet_col='Indicator',
    orientation='h',
    color='Indicator',
    color_discrete_sequence=["#1191ed", "#2ca02c", "#d62728", "#b274ec"],
    title='<b>Top 10 Balanced Countries Across Economy, Health, Education & Digitalization',
    subtitle = 'This chart compares the top 10 countries based on normalized scores across GDP per capita, Education Exp, Health Exp, and internet usage.<br>It highlights which countries are most balanced and advanced across these key development indicators.',
    width=950,
    height=500
)

# Layout adjustments
fig.update_layout(
    title_font_family="Helvetica",
    title_font_size=20,
    title_subtitle_font_size = 14,
    font=dict(family='Helvetica', size=14, color="#1A1A1A"),
    showlegend=False,
    margin={'t':170}
)

# Update all annotation labels (font size and color)
fig.for_each_annotation(lambda a: a.update(font=dict(size=12, color="#1A1A1A")))
# Remove all individual x-axis label and use a single clean label for the entire figure
fig.for_each_xaxis(lambda x: x.update(title_text=None))

# y-axis label
fig.update_layout(yaxis_title="Country")

# X-axis label styling
fig.add_annotation(
    text="Normalized Score (0–1)",
    xref="paper",
    yref="paper",
    x=0.5,
    y=-0.20,
    showarrow=False,
    font=dict(size=16, color="#1A1A1A", family="Helvetica")
)
fig.show()